name: CI/CD with Docker Compose and Blue-Green Deployment

on:
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Add user to Docker group
        run: |
          sudo usermod -aG docker $USER
          newgrp docker
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}

      - name: List build directory
        run: ls -al build/libs

      - name: Log in to GitHub Container Registry
        run: |
          set -x
          echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin
      - name: Build Docker image
        run: |
          set -x
          docker build --platform linux/amd64 --build-arg SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_TOKEN }} --progress=plain -t ghcr.io/${{ github.repository_owner }}/sumda-be-dev:latest .
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}

      - name: Push Docker image to GHCR
        run: |
          set -x
          docker push ghcr.io/${{ github.repository_owner }}/sumda-be-dev:latest

  setting:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
      - name: Add EC2 host to known_hosts
        run: |
          ssh-keyscan -H ${{ secrets.EC2_BACK_BLUE }} >> ~/.ssh/known_hosts
      - name: Verify SSH connection
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.EC2_USER }}@${{ secrets.EC2_BACK_BLUE }} echo "SSH connection successful"
      - name: Create .env file on EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.EC2_USER }}@${{ secrets.EC2_BACK_BLUE }} << EOF
            echo 'DB_URL=${{ secrets.DB_URL }}' > /home/${{ secrets.EC2_USER }}/.env
            echo 'DB_USERNAME=${{ secrets.DB_USERNAME }}' >> /home/${{ secrets.EC2_USER }}/.env
            echo 'DB_PASSWORD=${{ secrets.DB_PASSWORD }}' >> /home/${{ secrets.EC2_USER }}/.env
            echo 'OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}' >> /home/${{ secrets.EC2_USER }}/.env
            echo 'AIR_PUBLIC_API_KEY=${{ secrets.AIR_PUBLIC_API_KEY }}' >> /home/${{ secrets.EC2_USER }}/.env
            echo 'WEATHER_PUBLIC_API_KEY=${{ secrets.WEATHER_PUBLIC_API_KEY }}' >> /home/${{ secrets.EC2_USER }}/.env
            echo 'SENTRY_DSN=${{ secrets.SENTRY_DSN }}' >> /home/${{ secrets.EC2_USER }}/.env
            echo 'SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_TOKEN }}' >> /home/${{ secrets.EC2_USER }}/.env
            echo 'SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KAKAO_CLIENT_ID=${{ secrets.SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KAKAO_CLIENT_ID }}' >> /home/${{ secrets.EC2_USER }}/.env
            echo 'JWT_SECRET=${{ secrets.JWT_SECRET }}' >> /home/${{ secrets.EC2_USER }}/.env
          EOF
      - name: Pull Docker image and run on EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.EC2_USER }}@${{ secrets.EC2_DEV_HOST }} << EOF
            docker login ghcr.io -u ${{ github.repository_owner }} --password ${{ secrets.GHCR_TOKEN }}
            docker volume prune -f
            docker pull ghcr.io/${{ github.repository_owner }}/sumda-be-dev:latest
            docker stop sumda-be || true
            docker rm sumda-be || true
            docker run -d -p 8080:8080 --name sumda-be --env-file /home/${{ secrets.EC2_USER }}/.env ghcr.io/${{ github.repository_owner }}/sumda-be-dev:latest
          EOF

  deploy:
    runs-on: ubuntu-latest
    needs: setting

    steps:
    - name: copy docker-compose.blue.yml to remote server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_BACK_BLUE }}
        username: ubuntu
        key: ${{ secrets.EC2_KEY }}
        port: 22
        source: "./docker-compose.blue.yml"
        target: "/home/ubuntu/"
        tar_exec: false
        strip_components: 0

    - name: copy docker-compose.green.yml to remote server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_BACK_BLUE }}
        username: ubuntu
        key: ${{ secrets.EC2_KEY }}
        port: 22
        source: "./docker-compose.green.yml"
        target: "/home/ubuntu/"
        tar_exec: false
        strip_components: 0

    - name: copy deploy.sh to remote server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_BACK_BLUE }}
        username: ubuntu
        key: ${{ secrets.EC2_KEY }}
        port: 22
        source: "./deploy.sh"
        target: "/home/ubuntu/"
        tar_exec: false
        strip_components: 0

    - name: Execute deploy.sh script remotely
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_BACK_BLUE }}
        username: ubuntu
        key: ${{ secrets.EC2_KEY }}
        port: 22
        script: |
          chmod +x /home/ubuntu/deploy.sh
          /home/ubuntu/deploy.sh